### ISSUE TITLE
The Github Stats is out of date?

### ISSUE THREAD

**Issue by yangzj1992** [johnmpotter/npm-trends#10]
For example：

http://www.npmtrends.com/react-vs-vue

Both projects state is not inconsistent with the actual situation. (The stars and open issues)

Is the http://proxy.npmtrends.com/?url=XXX API out of date and no longer update?

**Comment by johnmpotter** [comment]
Thanks for pointing that out, i'll check it out and see what the issue is!

**Comment by johnmpotter** [comment]
Fixed the issue with the cache on the proxy (#11), so now the stats should be good to go. For some reason github's api returns the wrong open issue count, but can't do anything about that. Thanks again for bringing this up! 🙂
