### ISSUE TITLE
You are hitting rate limits at GitHub

### ISSUE THREAD

**Issue by vicary** [johnmpotter/npm-trends#116]
I tried to look at [this comparison](https://www.npmtrends.com/cross-fetch-vs-isomorphic-fetch-vs-node-fetch-vs-whatwg-fetch) and got nothing, opening dev tools shows a 403 error. See image below.

![image](https://user-images.githubusercontent.com/85772/126453957-9ed9e1af-66af-4419-bf56-d1be9b17c9a2.png)

**Comment by hugotown** [comment]
same thing here, cheers

**Comment by mahnunchik** [comment]
same 😢

**Comment by mahnunchik** [comment]
Related https://github.com/johnmpotter/npm-trends/issues/114

**Comment by mahnunchik** [comment]
Related https://github.com/johnmpotter/npm-trends/issues/113

**Comment by johnmpotter** [comment]
Hey there, sorry about the errors! I cache requests on the proxy, but github limits my key to 5,000 calls an hour so sometimes we hit that. Tried creating multiple GH accounts but they flagged me 😂. Let me see if there's anything else I can do! This is mainly due to moving away from npms because we saw instability there, but I may need to figure out a hybrid approach with some sort of fallback so we don't run into this issue.

**Comment by mahnunchik** [comment]
@johnmpotter maybe github may extend limit for you?

**Comment by vicary** [comment]
@johnmpotter not sure about your running budget, but probably works by queuing throttled updates behind the scene, while serving metrics from database with last update time displaying somewhere?

**Comment by CallMeLaNN** [comment]
Other than fallback or error message, it might be helpful if you can prevent it from going back to home page. Usually we'll click reload or reenter the URL as a kind of retry but end up missing all listed packages.

**Comment by vicary** [comment]
@CallMeLaNN Hey that's a pretty great idea and I'd like to have that too. I think it's better off tracking your feature request in a separate issue, so in case this one get closed for some reason people can still work on yours.

**Comment by ma-nish** [comment]
Request URL: https://proxy.npmtrends.com/?url=https://api.github.com/repos/ReactTraining/react-media
Request Method: GET
Status Code: 403 Forbidden

{
  "message": "API rate limit exceeded for user ID 5359194.",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}

**Comment by CarlosOrozc** [comment]
I had the same error I loaded the page in incognito mode and it worked for me.
![image](https://user-images.githubusercontent.com/8071575/128724700-2d8529ab-5c7e-4fde-890b-d5b8d5fb71db.png)

**Comment by johnmpotter** [comment]
I just updated how we fetch data to avoid the GitHub API if we can so we don't hit the limits. We now attempt to fetch the data from npms first (they have GitHub data in their response) and only go to the GitHub API as a fallback if npms is down. This update should improve the stability of that app, but i'm going to keep any eye out for any issues. Thanks for all the issue reporting and feedback!
