### ISSUE TITLE
just doesn't work

### ISSUE THREAD

**Issue by alexey-sh** [johnmpotter/npm-trends#12]
Nothing is shown.
<img width="1270" alt="2017-07-27 1 09 04" src="https://user-images.githubusercontent.com/1584156/28638971-5fc2e958-7268-11e7-80bf-b23dee9ce7a7.png">

**Comment by alexey-sh** [comment]
https://api.npms.io/v2/package/angular?url=http%3A%2F%2Fapi.npms.io%2Fv2%2Fpackage%2Fangular

failed

**Comment by johnmpotter** [comment]
Thanks a lot for letting me know @alexey-sh! It seems to be working now, may have been an issue with the npm api.

**Comment by alexey-sh** [comment]
@johnmpotter rly? let's think that the problem on my side and keep the issue closed.
<img width="1043" alt="2017-08-07 12 40 44" src="https://user-images.githubusercontent.com/1584156/29015000-d87578b2-7b6d-11e7-8c98-fa74ad4f8771.png">
