### ISSUE TITLE
Site acting up? Keeps auto refreshing to blank search

### ISSUE THREAD

**Issue by AckerApple** [johnmpotter/npm-trends#15]
The npmtrends.com website in auto refreshes to an empty search at the point of submitting any search OR even tapping on a "Popular" link.

Tested failing within:
- Chrome, Safari, and Firefox  on Mac
- Safari and Chrome on iPhone iOS 10

I assume, seeing that the HTTPS is not working, that perhaps this might be related?

I use this website frequent enough to know it was just working within a day or so

**Comment by AckerApple** [comment]
Issue seems to have subsided

**Comment by doug2k1** [comment]
Hi. It's happening again. Requests to api.npms.io are returning status code 522.
