### ISSUE TITLE
API and assets not loading

### ISSUE THREAD

**Issue by KrisBraun** [johnmpotter/npm-trends#16]
The site is currently broken. Looks like at least a couple issues:

- Assets (images and CSS) are not loading
- api.npms.io requests are blocked by CORS failures

![screen shot 2018-04-24 at 1 45 08 pm](https://user-images.githubusercontent.com/1422164/39204451-d3f5524c-47c5-11e8-920d-fa9fd86daffe.png)

**Comment by johnmpotter** [comment]
Thanks for letting me know! It's working now!
