### ISSUE TITLE
NPM Trends fails to load and flickers

### ISSUE THREAD

**Issue by dance2die** [johnmpotter/npm-trends#18]
### What?
The site loads but fails to search or load Popular trends as shown in the image below.

### How to reproduce
Click on Popular links or do a search

![npmtrends not working - 2018 05 08](https://user-images.githubusercontent.com/8465237/39780469-5bc2424c-52da-11e8-9900-bc5242ce8e86.gif)

**Comment by evolutionxbox** [comment]
There is a server error

```console
api.npms.io/v2/package/react?url=http%3A%2F%2Fapi.npms.io%2Fv2%2Fpackage%2Freact:1

Failed to load resource: the server responded with a status of 500 ()
```

**Comment by tsongas** [comment]
I'm also getting this error after entering `mobx`.

**Comment by johnmpotter** [comment]
Sorry, forgot to close this back when i fixed it. Thanks a lot for letting me know about it!

**Comment by rkesters** [comment]
@johnmpotter This is happening again.

**Comment by johnmpotter** [comment]
@rkesters Thanks for letting me know! I just restarted our proxy and seems to be working again now!

**Comment by williamcameron** [comment]
@johnmpotter This is happening again.

**Comment by BJS-kr** [comment]
happening again...

**Comment by StaceyD22** [comment]
Annnnnd again

![image](https://user-images.githubusercontent.com/52892750/231852027-6eebabe9-fabd-424e-af29-bfc6718da371.png)
