### ISSUE TITLE
Weird download counts

### ISSUE THREAD

**Issue by icebob** [johnmpotter/npm-trends#19]
Hi,

It shows very strange download counts for this week:
![image](https://user-images.githubusercontent.com/306521/41000152-5c55215e-690d-11e8-8e70-eacaeb1a9649.png)
What's happened?

**Comment by Brantron** [comment]
I'm seeing the same thing

![screen shot 2018-06-05 at 9 11 55 pm](https://user-images.githubusercontent.com/3149916/41010390-19a999d2-6905-11e8-9ad9-6d7a04a278fb.png)

**Comment by jmlivingston** [comment]
Seeing the same problem. Assuming perhaps GitHub's API changed?

**Comment by BobbyBabes** [comment]
Yeah, June the 3rd the aliens visited and abducted Node developers for their projects.
But it was also National Itch Day, Love Conquers All Day, National Egg Day, World Clubfoot Day, National Chocolate Macaroon Day, Impersonate Authority Day, Chimborazo Day, and Repeat Day (except for npm package downloads).

![npmtrends com___screenshot_20180705_114512](https://user-images.githubusercontent.com/22870070/42316029-15543184-8049-11e8-95a8-420967a611b0.png)

**Comment by icebob** [comment]
Yes, it's weird, but I close it because it is not an issue for this repo, it was a global NPM issue.

**Comment by NullMDR** [comment]
It is caused by npm's incidents. FYI https://status.npmjs.org/incidents/b4ktc38pypd1
