### ISSUE TITLE
Some packages missing Github stats

### ISSUE THREAD

**Issue by mcmo** [johnmpotter/npm-trends#2]
Great site for comparing NPM package downloads!  However, some packages do not provide the Github stats below the chart.  For these, the link tag is also missing the href to the Github repo.  One example is ramda.

![image](https://cloud.githubusercontent.com/assets/836142/12847137/c7f844b2-cbd6-11e5-9fbb-0901e7780512.png)

**Comment by johnmpotter** [comment]
I'm glad you like it! 

Thanks for letting me know about that issue, it looks like we exceeded Github's rate limit at one point and cached those error responses. I cleared the cache for now, so it should be working as expected. I'll figure out how to prevent this from happening in the future. Thanks again!
