### ISSUE TITLE
Question on Angular downloads 

### ISSUE THREAD

**Issue by xuv** [johnmpotter/npm-trends#20]
I don't think this is a bug, but I'd be curious to know why the download count of Angular packages doubled after the npm crash, as this graph shows:

![screen shot 2018-07-18 at 14 50 34](https://user-images.githubusercontent.com/192539/42905060-ef1eba32-8aa4-11e8-9453-f9d3823a18cf.png)

Anyone has any idea?

**Comment by johnmpotter** [comment]
Good question, not a holiday so i'm not sure!

I'm going to close this since it was awhile back
