### ISSUE TITLE
size of npm package are missing.

### ISSUE THREAD

**Issue by Shiv-Dangi** [johnmpotter/npm-trends#21]
I love this website and work done by you, most of the time I use this website to compare different npm packages. package size is one criterion for me to select an npm package and I think the same thing applies to most of the developers. generally, I use [bundlephobia](https://bundlephobia.com/result?p=pdfjs@2.0.0) for checking the size of the package which provide minified size as well as minified + gzipped size. if you can provide the same data somewhere on your website.

**Comment by johnmpotter** [comment]
Sorry for the delay on this, just added the bundle size badge to the table. It's live now!  

https://www.npmtrends.com/@angular/core-vs-react-vs-vue
