### ISSUE TITLE
Recived 500 in console

### ISSUE THREAD

**Issue by Frozzy6** [johnmpotter/npm-trends#24]
1.  Open [link](https://www.npmtrends.com/node-sass-vs-less-vs-autoprefixer-vs-postcss-loader-vs-postcss-preset-env)
2. Open console.
![image](https://user-images.githubusercontent.com/6423399/45018008-b7e62700-b031-11e8-85cc-cea64d87162b.png)

**Comment by tsongas** [comment]
Happening to me too.

**Comment by blueberry6401** [comment]
And this's happening again.

**Comment by johnmpotter** [comment]
I believe this is fixed now, thank you for letting me know about it!
