### ISSUE TITLE
No chart displayed (OS X 10.11.5 - Safari 9.1.1)

### ISSUE THREAD

**Issue by jbpenrath** [johnmpotter/npm-trends#3]
I'm using Safari 9.1.1 on OS X 10.11.5
There is an error which blocks the rendering of downloads chart.

The dev console throws an exception concerning the function `compare` :
`Error: Invalid Date - Sun Dec 06 2015 00:00:00 GMT+0100 (CET)`.

<img width="798" alt="capture d ecran 2016-05-28 a 16 25 42" src="https://cloud.githubusercontent.com/assets/9265241/15627848/37db5d32-24f1-11e6-90a3-98c27b388a75.png">

**Comment by bourrulebarbu** [comment]
+1

**Comment by johnmpotter** [comment]
Thanks a lot for letting me know @jbpenrath! That's what I get for not testing it on Safari. It should be working now! 👍
