### ISSUE TITLE
unable to display single large html page in multiple page with proper margin using jspdf

### ISSUE THREAD

**Issue by sudip2019** [johnmpotter/npm-trends#32]
jspdf is very impressive in producing pdf content in multiple pages.however issue appear when to split a large html page(div content) .Visited multiple issue list related to jspdf but didnt find any solution which help to split a large html page(div content) to be splitted properly in multiple pages.page break comes inside any table or paragraph which distorts the entire html page.Content are placed properly in all pdf pages but wherever page break comes,there is break inside the content.There is no way to give header and footer to all pages in pdf.please guide for urgent delivery for my project.

**Comment by johnmpotter** [comment]
Hey @sudip2019, you'll want to post this issue to the [jspdf github repository](https://github.com/MrRio/jsPDF) if you still need help on it. 

I'm going to close this issue, because it's not related to NPM Trends. We just show the download counts. 🙂
