### ISSUE TITLE
Comparisons are not correct.

### ISSUE THREAD

**Issue by timothymarois** [johnmpotter/npm-trends#35]
https://www.npmtrends.com/datatables-vs-footable-vs-tabulator

tabulator repo is incorrect. You should be using this repo:
https://github.com/olifolkerd/tabulator

Not https://github.com/codenautas/tabulator

**Comment by johnmpotter** [comment]
The comparisons are based on the npm package name. It looks like the package name for the repo you're interested in is: "tabulator-tables". 

This should give you what you're looking for: https://www.npmtrends.com/datatables-vs-footable-vs-tabulator-tables
