### ISSUE TITLE
Searching for 'react' fails

### ISSUE THREAD

**Issue by BBKolton** [johnmpotter/npm-trends#37]
Reproduction: 
Try to visit https://www.npmtrends.com/react
Page redirects to homepage instead of showing chart
OR
Create a chart with any package
Try to add react
Page fails to add react and shows previous chart

**Comment by seanf** [comment]
@BBKolton Is this still happening for you? Seems to be okay now.

**Comment by BBKolton** [comment]
Yep, seems good! Thanks
