### ISSUE TITLE
Charts are empty after being hovered, only filled when hovering the chart again (Firefox 50.0a1)

### ISSUE THREAD

**Issue by MoOx** [johnmpotter/npm-trends#4]
- Open a trend with Firefox 50 (nightly) - maybe with others versions too.
- hover the chart
- hover another part of the page
- the chart is empty (need to hover to see the content again).

No error in the browser console.

**Comment by johnmpotter** [comment]
Thanks for letting me know, I'll fix that asap! 👍

**Comment by johnmpotter** [comment]
I've updated a few libraries that may have caused this. I'm not able to replicate the issue, so fingers crossed that it's fixed. More than happy to dive into it again if you're still seeing it though. 🙂
