### ISSUE TITLE
GitHub Stars are missing "k" suffix

### ISSUE THREAD

**Issue by cinemast** [johnmpotter/npm-trends#43]
E.g: https://www.npmtrends.com/milligram-vs-picnic-vs-pure-css-vs-skeleton-css

purce-css has > 20k stars, it is displayed as it has 20 stars.

**Comment by cinemast** [comment]
It appears the wrong repository is linked: https://github.com/pure-css/pure

**Comment by rnd256** [comment]
You should be looking at the npm package `purecss`; not `pure-css`.
https://www.npmtrends.com/pure-css-vs-purecss
