### ISSUE TITLE
Scoped packages?

### ISSUE THREAD

**Issue by clavecoder** [johnmpotter/npm-trends#5]
[Angular 2](http://stackoverflow.com/questions/36667258/understanding-npm-package-prefix-angular-router) has started using [scoped packages](https://docs.npmjs.com/misc/scope), but **npm trends** doesn't seem to pick them up. Can they be supported so react can be compared with it?

**Comment by johnmpotter** [comment]
Looks like we're waiting on the downloads-count api to support it, then I'll definitely make sure npm trends can handle that! https://github.com/npm/download-counts/issues/23

**Comment by tberghuis** [comment]
Looks like it is now implemented http://blog.npmjs.org/post/159539048360/scope-support-in-search-and-download-stats

**Comment by johnmpotter** [comment]
@tberghuis Sweet, thanks for letting me know! I'll see if I can get it up and running this weekend 👍

**Comment by johnmpotter** [comment]
Thanks for being patient on this, finally got scoped packages working 👍

http://www.npmtrends.com/@angular/router-vs-angular-ui-router

But man, I hate how they're making the URLs look. 😉
