### ISSUE TITLE
cors errors

### ISSUE THREAD

**Issue by velohomme** [johnmpotter/npm-trends#51]
![image](https://user-images.githubusercontent.com/1175924/69396091-02cf7700-0c96-11ea-89c0-06adfeb98ff6.png)

**Comment by johnmpotter** [comment]
Thanks for letting me know! Not sure why this happens occasionally. I just updated the proxy so hopefully that fixes this error.

**Comment by tdranv** [comment]
Still receiving the error.

> Access to fetch at 'https://proxy.npmtrends.com/?url=https://api.npms.io/v2/package/react' from origin 'https://www.npmtrends.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
