### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [johnmpotter/npm-trends#52]
Whenever I search for a package, it adds it - and then immediately refreshes the page to the blank initial state?

**Comment by avindra** [comment]
Ditto. Something seems broken

**Comment by stearruda** [comment]
I believe it's still broken.
Any news about that?

**Comment by jsejcksn** [comment]
This appears to be a CORS issue with `proxy.npmtrends.com`. The console output shows these messages for each package name in the path of package names to compare:

> Access to XMLHttpRequest at 'https://proxy.npmtrends.com/?url=https://api.npms.io/v2/package/react' from origin 'https://www.npmtrends.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
>
> GET https://proxy.npmtrends.com/?url=https://api.npms.io/v2/package/react net::ERR_FAILED

**Comment by raulmarindev** [comment]
I get this kind of error message when selecting a package from the results list:
> Access to fetch at 'https://proxy.npmtrends.com/?url=https://api.npms.io/v2/package/grunt' from origin 'https://www.npmtrends.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> proxy.npmtrends.com/?url=https://api.npms.io/v2/package/grunt:1

**Comment by h0jeZvgoxFepBQ2C** [comment]
Somehow it worked fine for some time.. But now it's broken again :(

**Comment by wang1212** [comment]
I ran into the same problem today！
