### ISSUE TITLE
[Feature Request] Show color in table as well

### ISSUE THREAD

**Issue by Svish** [johnmpotter/npm-trends#53]
In the graph you're using colors in the graph, and each name has its color infront of it as a rectangle.

It would be very helpful if this color was also shown in the stats table, for example as a square/circle in front of the package name in the table:

![image](https://user-images.githubusercontent.com/142162/69645543-9faf5d00-1066-11ea-9f4e-08108f24509f.png)

**Comment by johnmpotter** [comment]
Great idea, just added this!
