### ISSUE TITLE
npmtrend.com comparison doesn't work

### ISSUE THREAD

**Issue by dudiharush** [johnmpotter/npm-trends#66]
**Selecting a package name** from the input field's dropdown or by clicking on one of the links don't result in displaying the download stats and the downloads graph, but **causes a redirect to the root of the site**, npmtrends.com

**Comment by wdoug** [comment]
I see requests to `https://proxy.npmtrends.com` are failing. Mine was showing CORS errors, but when I actually go to that domain the whole thing seems like it might be down...?

**Comment by brendanmatkin** [comment]
I see the same thing as @wdoug... a Heroku application error: 

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
> `heroku logs --tail`

**Comment by johnmpotter** [comment]
Thanks for letting me know about this, once in awhile we have issues with the API's we use. Should be working now!
