### ISSUE TITLE
Stats from GitHub are incorrect

### ISSUE THREAD

**Issue by Matt-Butler** [johnmpotter/npm-trends#7]
![incorrect_stars](https://cloud.githubusercontent.com/assets/8146159/20972624/13cd9232-bc5b-11e6-9b06-19d271f6ad06.gif)

**Comment by johnmpotter** [comment]
Hey Matt, thanks for letting me know, i'll look into that!

**Comment by johnmpotter** [comment]
Fixed the issue with the cache on the proxy (#11), so now the stats should be good to go. For some reason github's api returns the wrong open issue count, but can't do anything about that. 

Thanks again for letting me know about this! 😃

**Comment by Matt-Butler** [comment]
Awesome, nice work John!
