### ISSUE TITLE
XMLHttpRequest has been blocked by CORS policy

### ISSUE THREAD

**Issue by avevlad** [johnmpotter/npm-trends#71]
Access to XMLHttpRequest at 'https://proxy.npmtrends.com/?url=https://api.npms.io/v2/package/react-sticky' from origin 'https://www.npmtrends.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![image](https://user-images.githubusercontent.com/2889662/79598750-2388e500-80ed-11ea-8808-b789560cb50c.png)

**Comment by johnmpotter** [comment]
Hey @avevlad, thanks for letting me know about this! I'm not sure what the issue was but it seems to be working for me right now. Do you mind checking if you're still having the issue?

**Comment by avevlad** [comment]
@johnmpotter works correctly :) Thank you so much for your work!
