### ISSUE TITLE
larger download count is on wrong position

### ISSUE THREAD

**Issue by myth2loki** [johnmpotter/npm-trends#8]
Go to this page http://www.npmtrends.com/react-native-vs-cordova-vs-weex-vs-react
look for jan 1 react has 500 thousand download count, it is larger than the others, look at jan 1 8 15 22, they are on the wrong position.

**Comment by johnmpotter** [comment]
Hey @myth2loki, sorry for the slow response, you're absolutely right, I believe the everything is off by 1 week. Thanks a lot for letting me know, I'll fix this as soon as I get a chance! 🙂

**Comment by johnmpotter** [comment]
Updated the date.js library and I believe this is now fixed 👍
