### ISSUE TITLE
Bug in counting downloads?

### ISSUE THREAD

**Issue by beenotung** [johnmpotter/npm-trends#82]
From the graph, the download count of (all?) packages drops on the December. Is that something wrong in the count? Or it's really the developers and CI/CD machines were putting off work to celebrate the Christmas for the whole month?

![1](https://user-images.githubusercontent.com/6007292/90528418-2d0e8080-e1a5-11ea-9276-3c4fee2054d2.png)

**Comment by beenotung** [comment]
My initial guess is the date.getMonth() forgot to add 1?

**Comment by redbar0n** [comment]
Maybe it could be related to this?

From npmtrends.com: "The npm package download data comes from npm's download counts api"

Which is: https://github.com/npm/download-counts

But it states:
"Note! This code base isn't what npm uses to serve download counts anymore, and its documentation is likely to drift out of correctness as time passes. See the registry API documentation for up-to-date usage info."

**Comment by llaenowyd** [comment]
Hopefully it's just a December thing, I find the site super helpful.

**Comment by johnmpotter** [comment]
I was surprised when I first saw this phenomenon as well. That's an actual dip in downloads during the December holidays. 

If we look at Jest for this year, here's Friday December 25 vs the Friday December 11:

{downloads: 1738352, day: "2020-12-11"} vs {downloads: 386357, day: "2020-12-25"}

The drop is most dramatic on Christmas day, but you see lower downloads in the week before and after Christmas.

**Comment by beenotung** [comment]
Thanks for the confirmation
