### ISSUE TITLE
[BREAKING] Deployment disabled

### ISSUE THREAD

**Issue by mxstbr** [johnmpotter/npm-trends#87]
Visiting www.npmtrends.com shows this Vercel error:

![Screenshot 2020-09-29 at 10 38 49](https://user-images.githubusercontent.com/7525670/94533820-f9148980-023f-11eb-9935-966224143eaf.png)

**Comment by naruepanart** [comment]
+1

**Comment by johnmpotter** [comment]
Fixed, thanks for letting me know! 🙌
