### ISSUE TITLE
Scale the Y-axis so that zero is the lowest value

### ISSUE THREAD

**Issue by roryokane** [johnmpotter/npm-trends#9]
It is harder to understand how much the downloads fluctuate when the Y-axis of the chart is scaled to show only the line. When I saw this chart:

![normalize.css downloads chart example](https://cloud.githubusercontent.com/assets/79168/23618467/634e0816-025e-11e7-922d-7a4642f52764.png)

It made me think, "Wow, almost everybody stopped downloading it around Jan 1. Did NPM break around that time?"

But eventually, I noticed that the values on the Y-axis range from 40,000 to 110,000. So there were still 45,000 downloads on Jan 1. That makes more sense.

I tried to understand how much the downloads fluctuated compared to the overall number of downloads, but it required mental math. I had to hold in my head the numbers 60,000, 40,000, 0 and compare them. Requiring mental calculations defeats the purpose of showing a graph, which is to visualize numbers intuitively.

You can solve this problem and avoid confusion by making the downloads axis start at 0 instead of at the lowest value for that time frame. The changes between weeks will be less visible, but the overall numbers will be communicated more accurately and won't mislead people who don't look at the chart closely.

**Comment by johnmpotter** [comment]
Hey @roryokane, thanks a lot for your feedback on this, I really appreciate you taking the time to let me know your thoughts! I haven't had a lot of time recently to spend on this project, but as soon as I get some time to revisit it, i'll definitely look into this. 

I agree that it can be misleading when it comes to large dips like the one you see above (which interestingly can be seen across modules as it occurs right around the December holidays - Christmas and New Years). There Is a bug that I haven't had a chance to fix yet, where the stats are off one week. So the very bottom of the dip is actually the week of December 25th. 

Anyways, thanks again for the feedback, I'll look into this asap!
