### ISSUE TITLE
Searching is broken for many packages

### ISSUE THREAD

**Issue by wenfangdu** [johnmpotter/npm-trends#92]
![npm-trends](https://user-images.githubusercontent.com/28700378/99019860-4783aa80-2598-11eb-8f1c-a485dcf79aac.gif)

**Comment by gramotei** [comment]
Confirm

**Comment by johnmpotter** [comment]
Sorry, we should throw an error for this, but it looks like the api we use from npms is down right now. I'll update this issue once it's back up. https://github.com/npms-io/npms

**Comment by meatflavourdev** [comment]
I'm not sure if this is the same issue-- it appears the website is totally inoperable. If you select a package, it shows nothing and kicks you back to the root URL. Running the project locally in dev mode gives this error: 
> **Unhandled Runtime Error**
TypeError: Failed to fetch

I tried another mirror, I tried a mobile browser with a different internet provider. I tried Brave, Chrome, Edge, Chrome Mobile. Nothing works. You mentioned the API is down. A request to 
`https://api.npms.io/v2/package/react`
seems to confirm this as it returns 
```javascript
{
  "code": "NOT_FOUND",
  "message": "Module not found"
}
```
For, as far as I can tell, any package name. Boo 😥

**Comment by alex-drocks** [comment]
Hello, I confirm it stopped working for me today. Btw thanks a lot for this tool Ive been making good decisions like you were as a starting developper.

**Comment by Jolg42** [comment]
Yes npms is broken indeed https://github.com/npms-io/npms/issues/44

**Comment by x35a** [comment]
Do we have any alternatives to npm-trends ?

**Comment by Jolg42** [comment]
I think npms is not needed, the data there is not in great shape either (even when working) based on my research and on the issues in their repo.

I'll try to do a PR to remove it and keep all functionality 😃

**Comment by redbar0n** [comment]
Maybe it could be related to this?

From **npmtrends.com**: "The npm package download data comes from npm's download counts api"

Which is: https://github.com/npm/download-counts

But it states:
"Note! This code base isn't what npm uses to serve download counts anymore, and its documentation is likely to drift out of correctness as time passes. See the [registry API documentation](https://github.com/npm/registry/blob/master/docs/download-counts.md) for up-to-date usage info."

**Comment by redbar0n** [comment]
No, that is another bug.
But this one seems a bug in [npms.io](npms.io) which npm-trends uses: https://github.com/npms-io/npms/issues/46

**Comment by johnmpotter** [comment]
Just released an update to use the npm registry api instead of npms. npms provided some useful data that we don't get from npm registry, so we now build our own composite record with the additional data we need for the ui (similar to how npms does behind the scenes). https://github.com/johnmpotter/npm-trends/pull/96 

Thanks a lot @Jolg42 for your work on the PR with the suggestion to switch!
