### ISSUE TITLE
[Bug] Redirect to homepage

### ISSUE THREAD

**Issue by farzer** [johnmpotter/npm-trends#93]
when click to a comparison，it always to redirect to homepage

**Comment by x35a** [comment]
duplicating #92

**Comment by Jolg42** [comment]
It's interesting that there is also an infinite loop in the background
<img width="613" alt="Screen Shot 2020-11-16 at 10 48 41" src="https://user-images.githubusercontent.com/1328733/99237883-5cab4400-27f9-11eb-810d-5396d2772f5f.png">

**Comment by gitowiec** [comment]
This bug still blocks Trends usage! OMG how I now which module to install now?

**Comment by Jolg42** [comment]
@gitowiec Try Skypack Discovery :D
https://www.skypack.dev/blog/2020/10/introducing-skypack-discover/
https://www.skypack.dev/

**Comment by redbar0n** [comment]
@johnmpotter could you please look at this asap? This bug breaks most links to npmtrends.com and makes the service unusable.

**Comment by johnmpotter** [comment]
https://github.com/johnmpotter/npm-trends/pull/96 should improve stability on this
